interfaces:
- name: eno1
  description: Ethernet eno1
  type: ethernet
  state: up
  ipv4:
    enabled: false
  mtu: 9000
- name: eno2
  description: Ethernet eno2
  type: ethernet
  state: up
  ipv4:
    enabled: false
  mtu: 9000
- name: bond0
  description: Bond with ports eno1 and eno2
  type: bond
  state: up
  ipv4:
    enabled: false
  link-aggregation:
    mode: 802.3ad
    options:
      miimon: '100'
    port:
    - eno1
    - eno2
    mtu: 9000
- name: bond0.1306
  description: vlan1306 using bond0
  type: vlan
  state: up
  ipv4:
    dhcp: false
    address:
    - ip: 172.24.190.102
      prefix-length: 24
    enabled: true
  vlan:
    base-iface: bond0
    id: 1306
  mtu: 9000
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 172.24.190.1
    next-hop-interface: bond0.1306
dns-resolver:
  config:
    search:
    - pflex.sg.csc
    server:
    - 172.24.57.10
