 # Username for accessing PowerFlex system.	
 # Required: true
- username: "admin"
 # Password for accessing PowerFlex system.	
 # Required: true
  password: "ScaleIO123!"
 # System name/ID of PowerFlex system.	
 # Required: true
  systemID: "5d0fa4775df5670f"
 # REST API gateway HTTPS endpoint/PowerFlex Gateway IP for PowerFlex system.
 # Required: true
  endpoint: "https://172.24.188.211"
 # Determines if the driver is going to validate certs while connecting to PowerFlex REST API interface.
 # Allowed values: true or false
 # Required: true
 # Default value: true
  skipCertificateValidation: true 
 # indicates if this array is the default array
 # needed for backwards compatibility
 # only one array is allowed to have this set to true 
 # Required: false
 # Default value: false
  isDefault: true
 # defines the MDM(s) that SDC should register with on start.
 # Allowed values:  a list of IP addresses or hostnames separated by comma.
 # Required: true
 # Default value: none 
  mdm: "172.24.188.101,172.24.188.102"
 # Defines all system names used to create powerflex volumes
 # Required: false
 # Default value: none
 # AllSystemNames: "name1,name2"
