apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master1-bond1-configuration
spec:
  nodeSelector:
    kubernetes.io/hostname: "ocp-node2"
  desiredState:
    interfaces:
    - name: bond1
      description: Bond with ports eno3 and eno4
      type: bond
      state: up
      ipv4:
        dhcp: false
        enabled: false
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '100'
        port:
        - eno3
        - eno4
      mtu: 9000