apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "powerstore1k-nfs"
provisioner: "csi-powerstore.dellemc.com"
parameters:
  arrayID: "unique"
  FsType: "nfs"
  nasName: "iac"
  allowRoot: "false"

reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
