apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-pvc-snapshot-restore
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: dell-pflex-sc
  volumeMode: Filesystem
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: test-app-pvc-snapshot
---
apiVersion: v1
kind: Pod
metadata:
  name: powerflex-test-snapshot-pod
  namespace: default
spec:
  containers:
  - name: test
    image: docker.io/centos:latest
    command: [ "/bin/sleep", "3600" ]
    volumeMounts:
    - name: pvol1-powerflex
      mountPath: "/data1"
  volumes:
    - name: pvol1-powerflex
      persistentVolumeClaim:
        claimName: test-app-pvc-snapshot-restore