apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
  storageClassName: dell-pflex-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: powerflextestpod
  namespace: default
spec:
  containers:
  - name: test
    image: docker.io/centos:latest
    command: [ "/bin/sleep", "3600" ]
    volumeMounts:
    - name: pvol0-powerflex
      mountPath: "/data0"
  volumes:
    - name: pvol0-powerflex
      persistentVolumeClaim:
        claimName: test-app-pvc
