apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-set-selinux-for-hostpath-provisioner
  labels:
  machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: hostpath-provisioner.service
          enabled: true
          contents: |
            [Unit]
            Description=Set SELinux chcon for hostpath provisioner
            Before=kubelet.service
            [Service]
            Type=oneshot 
            RemainAfterExit=yes 
            ExecStart=/usr/bin/chcon -Rt container_file_t /var/data
            [Install]
            WantedBy=multi-user.target